# **Tensor**

Array -> 1 D

Matrix -> 2 D

Tesonr -> n D

*`1. Scalars: 0-dimentional tensor(a single number)`*
* Represents a single value, often used for simple metrics or contants.
    * **Loss value**: After a forward pass, the loss function computes a single scalar value indicating the difference between the predicted and actual outputs.

*`2. Vectors: 1-dimensional tensors(a list of numbers)`*
* Represents a sequence or a collection of values.
    * **Feature Vector**: In natural language processing, each word in a sentence may be represented as a 1D vector using embeddings.
    * A word embedding vector from a pre-trained model like Word2Vec or Glove.

*`3. Matrices: 2-dimensional tensors`*
* Represents tabular or grid-like data. 
    * **Grayscale images**: A Grayscale image can be represented as a 2D tensor, where each entry corresponds to the pixel intensity.

*`4. 3D Tensor: Coloured images`*
* Adds a third dimension, often used for stacking data. 
    * **RGB Images**: A single RGB image is represented as a 3D tensor (width X height X channels). 
    * RGB Image (e.g., 256 X 256): Shape [256, 256, 3]

*`5. 4D Tensors: Batches of RGB images`*
* Adds the batch size as an additional dimension to 3D data.
    * **Batches of RGB Images**: A dataset of coloured images is represented as a 4D tensor (batch size X width X height X channels). 
    * Example: A batch of 32 images, each of size `128X128` with 3 colour channels (RGB), would have shape `[32, 128, 128, 3]`.

*`6. 5D Tensor: Video data`* 
* Adds a time dimention for data that changes over time (e.g., video frames).
    * **Video Clips**: Represented as a sequence of frames, where each frame is an RGB image. 
    * Example: A Batch of 10 video clips, each with 16 frames of size 64X64 and 3 channels (RGB), would have shape [10, 16, 64, 64, 3]. 


### **Why are Tensors Useful?**

1. Mathematical Operations
    * Tensor enable efficient mathematical computations (addition, muliplication, dot product, etc.) necessary for neural network operations.
2. Representation od Real-world Data
    * Data like images, audio, videos, and text can be represented as tensors: 
        * *Images*: Represented as 3D tensors (width X height X channels).
3. Efficient Computations
    * Tensors are optimized for hardware acceleration, allowing computations on GPUs or TPUs, which are crucial for traning models. 


### **Where are Tensor used in Deep Learning?**

1. Data Storage
    * Training data (Images, text, etc.) is stored in tensors. 

2. Weights and Biases
    * The learnable parameters of neural network (weights, biases) are stored as tensors.

3. Matrix Operations
    * Neural networks involve operations like matrix multiplication, dot products, and broadcasting -- all performed using tensors.

4.  Training Process 
    * During forward passes, tensors flow through the network. 
    * Gradients, represented as tensor, are calculated during the backward pass. 

In [1]:
import torch
print(torch.__version__)

2.6.0


In [10]:
import platform
import torch

if torch.backends.mps.is_available():
    print("GPU is available!")
    print(f"GPU Name: Apple {platform.machine()} GPU")
else:
    print("GPU not available. Using CPU")


GPU is available!
GPU Name: Apple arm64 GPU


### *Creating a Tensor*

In [38]:
## Using Empty
a = torch.empty(2,3)

In [39]:
type(a)

torch.Tensor

In [40]:
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [42]:
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [43]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [44]:
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [45]:
#### Other ways

## arange
print("Using arange -> ", torch.arange(0,10))

print("Using linespace ->", torch.linspace(0, 100, 20))

print("Using eye ->", torch.eye(5))

print("Using full ->", torch.full((3,3), 5))

Using arange ->  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Using linespace -> tensor([  0.0000,   5.2632,  10.5263,  15.7895,  21.0526,  26.3158,  31.5789,
         36.8421,  42.1053,  47.3684,  52.6316,  57.8947,  63.1579,  68.4211,
         73.6842,  78.9474,  84.2105,  89.4737,  94.7368, 100.0000])
Using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### **Tensor Shapes**

In [46]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [47]:
x.shape

torch.Size([2, 3])

In [48]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [49]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [50]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [51]:
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

### **Tensor Data Types**

In [52]:
x.dtype

torch.int64

In [53]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [54]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [55]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [58]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


### **Mathematical Operations**

In [69]:
x = torch.rand(2,2)
x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [70]:
x + 2

tensor([[2.9969, 2.7565],
        [2.2239, 2.3023]])

In [71]:
x - 1

tensor([[-0.0031, -0.2435],
        [-0.7761, -0.6977]])

In [72]:
x * 3

tensor([[2.9907, 2.2695],
        [0.6717, 0.9070]])

In [73]:
x / 3

tensor([[0.3323, 0.2522],
        [0.0746, 0.1008]])

In [74]:
(x *100)//3

tensor([[33., 25.],
        [ 7., 10.]])

In [75]:
((x *100)//3)%2

tensor([[1., 1.],
        [1., 0.]])

In [76]:
x ** 2

tensor([[0.9938, 0.5723],
        [0.0501, 0.0914]])

### **Element wise operation**

In [77]:
a = torch.rand(2,3)
b = torch.rand(2,3)

a, b

(tensor([[0.1784, 0.8238, 0.5557],
         [0.9770, 0.4440, 0.9478]]),
 tensor([[0.7445, 0.4892, 0.2426],
         [0.7003, 0.5277, 0.2472]]))

In [78]:
a + b

tensor([[0.9229, 1.3130, 0.7983],
        [1.6774, 0.9717, 1.1950]])

In [79]:
a - b

tensor([[-0.5661,  0.3346,  0.3132],
        [ 0.2767, -0.0837,  0.7007]])

In [80]:
a * b

tensor([[0.1328, 0.4030, 0.1348],
        [0.6842, 0.2343, 0.2343]])

In [81]:
a/b

tensor([[0.2397, 1.6841, 2.2912],
        [1.3951, 0.8415, 3.8346]])

In [82]:
a**b

tensor([[0.2771, 0.9096, 0.8672],
        [0.9839, 0.6515, 0.9868]])

In [ ]:
a % b  ### values are less than 1. not make any sense 

tensor([[0.1784, 0.3346, 0.0706],
        [0.2767, 0.4440, 0.2063]])

In [85]:
c = torch.tensor([1, -2, 3, -4])
c

tensor([ 1, -2,  3, -4])

In [86]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [87]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [94]:
d = torch.tensor([1.9, 2.1, 3.5, 3.4, 4.6])

In [95]:
torch.round(d)

tensor([2., 2., 4., 3., 5.])

In [97]:
torch.ceil(d)

tensor([2., 3., 4., 4., 5.])

In [98]:
torch.floor(d)

tensor([1., 2., 3., 3., 4.])

In [101]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.1000, 3.0000, 3.0000, 3.0000])

### **Reduction Operaation**

In [125]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 3., 6.],
        [1., 5., 5.]])

In [126]:
torch.sum(e)


tensor(28.)

In [127]:
## Columns wise sum
torch.sum(e, dim=0)

tensor([ 9.,  8., 11.])

In [128]:
## Rows wise sum
torch.sum(e, dim=1)

tensor([17., 11.])

In [129]:
torch.mean(e), torch.mean(e, dim=0)

(tensor(4.6667), tensor([4.5000, 4.0000, 5.5000]))

In [130]:
torch.median(e)

tensor(5.)

In [131]:
torch.min(e), torch.max(e)

(tensor(1.), tensor(8.))

In [132]:
torch.std(e)

tensor(2.4221)

In [133]:
torch.var(e)

tensor(5.8667)

In [ ]:
torch.argmax(e)    ### Position of the max value in array

tensor(0)

In [135]:
torch.argmin(e)    ### Position of the min value in array

tensor(3)

### **Matrix Operations**

In [137]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

f,g

(tensor([[8, 4, 7],
         [2, 3, 8]]),
 tensor([[5, 6],
         [2, 9],
         [5, 0]]))

In [138]:
torch.matmul(f,g)

tensor([[83, 84],
        [56, 39]])

In [140]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

torch.dot(vector1, vector2)

tensor(11)

In [141]:
f

tensor([[8, 4, 7],
        [2, 3, 8]])

In [142]:
torch.transpose(f, 0, 1)

tensor([[8, 2],
        [4, 3],
        [7, 8]])

In [143]:
h = torch.randint(size = (3,3), low =0, high=10, dtype=torch.float32)
h

tensor([[4., 2., 7.],
        [1., 1., 5.],
        [4., 4., 1.]])

In [144]:
torch.det(h)

tensor(-38.)

In [146]:
torch.inverse(h)

tensor([[ 0.5000, -0.6842, -0.0789],
        [-0.5000,  0.6316,  0.3421],
        [ 0.0000,  0.2105, -0.0526]])

### **Comparison Operation**

In [150]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

i, j

(tensor([[6, 8, 4],
         [9, 0, 7]]),
 tensor([[9, 2, 7],
         [0, 2, 4]]))

In [151]:
i>j

tensor([[False,  True, False],
        [ True, False,  True]])

In [152]:
i<j

tensor([[ True, False,  True],
        [False,  True, False]])

In [153]:
i == j

tensor([[False, False, False],
        [False, False, False]])

In [154]:
i != j

tensor([[True, True, True],
        [True, True, True]])

In [155]:
i >= j

tensor([[False,  True, False],
        [ True, False,  True]])

In [157]:
i <= j

tensor([[ True, False,  True],
        [False,  True, False]])

### **Special functions**

In [165]:
k = torch.randint(size=(2,3), low=0, high=10, dtype = torch.float32)
k

tensor([[1., 0., 0.],
        [2., 2., 3.]])

In [166]:
torch.log(k)

tensor([[0.0000,   -inf,   -inf],
        [0.6931, 0.6931, 1.0986]])

In [167]:
torch.exp(k)

tensor([[ 2.7183,  1.0000,  1.0000],
        [ 7.3891,  7.3891, 20.0855]])

In [168]:
torch.sqrt(k)

tensor([[1.0000, 0.0000, 0.0000],
        [1.4142, 1.4142, 1.7321]])

In [169]:
torch.sigmoid(k)

tensor([[0.7311, 0.5000, 0.5000],
        [0.8808, 0.8808, 0.9526]])

In [170]:
torch.softmax((k), dim=0)

tensor([[0.2689, 0.1192, 0.0474],
        [0.7311, 0.8808, 0.9526]])

In [171]:
torch.relu(k)

tensor([[1., 0., 0.],
        [2., 2., 3.]])

### **Inplace Operation**

In [181]:
m = torch.rand(2,3)
n = torch.rand(2,3)

m,n

(tensor([[0.0277, 0.5662, 0.3503],
         [0.6555, 0.7667, 0.2269]]),
 tensor([[0.7555, 0.6458, 0.3673],
         [0.1770, 0.2966, 0.9925]]))

In [182]:
m + n 

tensor([[0.7832, 1.2120, 0.7176],
        [0.8325, 1.0633, 1.2194]])

In [183]:
m.add_(n)

tensor([[0.7832, 1.2120, 0.7176],
        [0.8325, 1.0633, 1.2194]])

In [184]:
m, n

(tensor([[0.7832, 1.2120, 0.7176],
         [0.8325, 1.0633, 1.2194]]),
 tensor([[0.7555, 0.6458, 0.3673],
         [0.1770, 0.2966, 0.9925]]))

In [185]:
torch.relu(m)

tensor([[0.7832, 1.2120, 0.7176],
        [0.8325, 1.0633, 1.2194]])

In [186]:
m.relu_()

tensor([[0.7832, 1.2120, 0.7176],
        [0.8325, 1.0633, 1.2194]])

### **Copying a Tensor**

In [187]:
a = torch.rand(2,3)
a

tensor([[0.2103, 0.1292, 0.1719],
        [0.9127, 0.6818, 0.1953]])

In [191]:
b = a
b

tensor([[0.2103, 0.1292, 0.1719],
        [0.9127, 0.6818, 0.1953]])

In [192]:
id(a), id(b)

(5078295936, 5078295936)

In [193]:
id(a) == id(b)

True

In [194]:
b = a.clone()

In [195]:
a, b

(tensor([[0.2103, 0.1292, 0.1719],
         [0.9127, 0.6818, 0.1953]]),
 tensor([[0.2103, 0.1292, 0.1719],
         [0.9127, 0.6818, 0.1953]]))

In [196]:
a[0][0] = 1000

In [197]:
a, b

(tensor([[1.0000e+03, 1.2920e-01, 1.7187e-01],
         [9.1269e-01, 6.8177e-01, 1.9534e-01]]),
 tensor([[0.2103, 0.1292, 0.1719],
         [0.9127, 0.6818, 0.1953]]))

In [198]:
id(a), id(b)

(5078295936, 5078773952)

### **Tensor Operations on GPU**

In [3]:
device = torch.device("mps") if torch.backends.mps.is_available() else torch.device("cpu")

device

device(type='mps')

In [4]:
torch.rand((2,3), device=device)

tensor([[0.0378, 0.9512, 0.5809],
        [0.8523, 0.6233, 0.6205]], device='mps:0')

In [5]:
a.to(device)

NameError: name 'a' is not defined

In [18]:
import time
import torch

size = 10000

matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

start_time = time.time()
result_cpu = torch.matmul(matrix_gpu1, matrix_gpu2)
# torch.mps.synchronize()
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")


print("\nSpeedup (CPU time / GPU time):", cpu_time/gpu_time)

Time on CPU: 2.1487 seconds
Time on GPU: 0.0071 seconds

Speedup (CPU time / GPU time): 304.3926774073699


### **Reshaping Tensor**

In [21]:
a = torch.ones(6,6)
a

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [22]:
a.reshape(9,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
b = torch.rand(2, 3, 4)
b

tensor([[[0.4694, 0.3624, 0.2785, 0.6683],
         [0.4147, 0.0610, 0.7419, 0.2872],
         [0.0551, 0.3664, 0.4693, 0.6676]],

        [[0.1816, 0.6959, 0.2322, 0.3429],
         [0.3078, 0.7151, 0.1778, 0.6338],
         [0.3967, 0.0098, 0.4859, 0.2476]]])

In [27]:
b.permute(2,0,1).shape  ### value of (2, 0, 1) is idx

torch.Size([4, 2, 3])

### **`unsqueeze`**

In [30]:
c = torch.rand(226, 226, 3)


In [ ]:
c.unsqueeze(0).shape   ### value of (0) is idx

torch.Size([1, 226, 226, 3])

In [40]:
d = torch.rand(1, 10, 20)
d.squeeze(0).shape

torch.Size([10, 20])

### **NumPy <==> PyTorch**

In [46]:
import numpy as np

In [47]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [48]:
b = a.numpy()
b

array([1, 2, 3])

In [49]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [50]:
torch.from_numpy(c)

tensor([1, 2, 3])