# **Training Pipeline**

In [33]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch.nn as nn

In [23]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [24]:
df.shape

(569, 33)

In [25]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

### **train test split**

In [26]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [27]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [28]:
y_train

287    B
159    B
496    B
401    B
432    M
      ..
289    B
538    B
465    B
363    B
105    M
Name: diagnosis, Length: 455, dtype: object

### **Label Encoding**

In [29]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [30]:
y_train

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,

### **Numpy arrays to PyTorch tensors**

In [46]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [63]:
y_train_tensor = torch.from_numpy(y_train).to(torch.float64)
y_test_tensor = y_test_tensor.to(torch.float64)

In [64]:
X_train_tensor.dtype

torch.float64

In [65]:
X_train_tensor.shape, y_train_tensor.shape

(torch.Size([455, 30]), torch.Size([455]))

### **Defining the model**

In [89]:
class MySimpleNN():

    def __init__(self, X):

        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias =   torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

In [90]:
class MySimpleNN(nn.Module):
    def __init__(self, num_features):

        super().__init__()

        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
        self.double()
    
    
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out
    
    

### **Important Parameter**

In [91]:
learning_rate = 0.1
epochs = 25

In [92]:
loss_function = nn.BCELoss()

### **Training Pipeline**

In [93]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6488684469474117
Epoch: 2, Loss: 0.5004535052725944
Epoch: 3, Loss: 0.4194658031026892
Epoch: 4, Loss: 0.3682716521263959
Epoch: 5, Loss: 0.33258758836915336
Epoch: 6, Loss: 0.3060560250939256
Epoch: 7, Loss: 0.2854125599737795
Epoch: 8, Loss: 0.2688005726617165
Epoch: 9, Loss: 0.25508177111094904
Epoch: 10, Loss: 0.2435171012986046
Epoch: 11, Loss: 0.23360451631933307
Epoch: 12, Loss: 0.22499023005685143
Epoch: 13, Loss: 0.2174172418407814
Epoch: 14, Loss: 0.21069401341358626
Epoch: 15, Loss: 0.20467463097951158
Epoch: 16, Loss: 0.19924580781099582
Epoch: 17, Loss: 0.19431811681583588
Epoch: 18, Loss: 0.18981992465405623
Epoch: 19, Loss: 0.1856931004943029
Epoch: 20, Loss: 0.18188991972530505
Epoch: 21, Loss: 0.1783707901352244
Epoch: 22, Loss: 0.17510255538432307
Epoch: 23, Loss: 0.17205721088829246
Epoch: 24, Loss: 0.16921091906202732
Epoch: 25, Loss: 0.16654324504422469


In [94]:
model.linear.weight, model.linear.bias

(Parameter containing:
 tensor([[ 0.1002,  0.1749,  0.3891,  0.1548,  0.1536,  0.0883,  0.1066,  0.1910,
           0.1699, -0.1397,  0.2141,  0.0254,  0.2384,  0.2182,  0.0141,  0.0689,
           0.0099,  0.0385,  0.0753, -0.2243,  0.3254,  0.3028,  0.2747,  0.1166,
           0.1136,  0.1235,  0.1884,  0.3740,  0.1772,  0.1880]],
        dtype=torch.float64, requires_grad=True),
 Parameter containing:
 tensor([-0.1616], dtype=torch.float64, requires_grad=True))

### **Evaluation**

In [95]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.89).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.573253333568573
