# **NN Module**

In [2]:
import torch
import torch.nn as nn

In [4]:
class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__()

        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)

        return out

In [6]:
features = torch.rand(10, 5)
features, features.shape

(tensor([[0.9404, 0.9879, 0.5891, 0.8964, 0.8303],
         [0.7368, 0.6186, 0.0451, 0.7570, 0.0915],
         [0.2019, 0.3859, 0.4950, 0.8208, 0.3294],
         [0.6473, 0.1590, 0.6150, 0.7457, 0.0260],
         [0.0050, 0.8023, 0.0745, 0.2342, 0.0859],
         [0.5426, 0.9764, 0.5733, 0.7899, 0.9072],
         [0.6275, 0.4808, 0.3131, 0.4304, 0.2355],
         [0.4304, 0.8000, 0.2034, 0.0841, 0.9743],
         [0.2484, 0.3059, 0.1792, 0.6200, 0.0089],
         [0.7416, 0.1497, 0.3536, 0.2022, 0.2453]]),
 torch.Size([10, 5]))

In [24]:
model = Model(features.shape[1])

model(features)

tensor([[0.6813],
        [0.6652],
        [0.6666],
        [0.6775],
        [0.6428],
        [0.6711],
        [0.6612],
        [0.6404],
        [0.6568],
        [0.6569]], grad_fn=<SigmoidBackward0>)

In [25]:
model.linear_1.weight, model.linear_1.bias

(Parameter containing:
 tensor([[ 0.3146, -0.3839, -0.4259, -0.4412, -0.3845],
         [ 0.0361,  0.1127, -0.1540, -0.3712, -0.1419],
         [ 0.1671,  0.0595,  0.2876,  0.2330, -0.1080]], requires_grad=True),
 Parameter containing:
 tensor([-0.1600,  0.3487, -0.0535], requires_grad=True))

In [26]:
model.linear_2.weight, model.linear_2.bias

(Parameter containing:
 tensor([[-0.2013,  0.0028,  0.4443]], requires_grad=True),
 Parameter containing:
 tensor([0.5592], requires_grad=True))

In [17]:
from torchinfo import summary

In [18]:
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [23]:
class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__()

        self.linear_1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear_2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()


    def forward(self, features):
        out = self.linear_1(features)
        out = self.relu(out)
        out = self.linear_2(out)
        out = self.sigmoid(out)


        return out

In [20]:
class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid(),
        )

    def forward(self, features):
        out = self.network(features)


        return out

In [27]:
model = Model(features.shape[1])

model(features)

tensor([[0.5318],
        [0.5361],
        [0.5729],
        [0.5985],
        [0.5313],
        [0.5288],
        [0.5554],
        [0.5047],
        [0.5665],
        [0.5699]], grad_fn=<SigmoidBackward0>)

In [28]:
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00