In [1]:
import torch

print(torch.__version__)

2.0.1


In [202]:
# Is MPS even available? macOS 12.3+
print(torch.backends.mps.is_available())

# was the current version pf PyTorch built with MPS activated?
print(torch.backends.mps.is_built())

True
True


In [203]:
import math

dtype = torch.float
device = torch.device("mps")

# Create random input and output data
x = torch.linspace(-math.pi, math.pi, 2000, device=device, dtype=dtype)
y = torch.sin(x)

# Randomly initialize weights
a = torch.randn((), device=device, dtype=dtype)
b = torch.randn((), device=device, dtype=dtype)
c = torch.randn((), device=device, dtype=dtype)
d = torch.randn((), device=device, dtype=dtype)

learning_rate = 1e-6
for t in range(2000):
    # Forward pass: compute predicted y
    y_pred = a + b * x + c * x ** 2 + d * x ** 3

    # Compute and print loss
    loss = (y_pred - y).pow(2).sum().item()
    if t % 100 == 99:
        print(t, loss)

# Backprop to compute gradients of a, b, c, d with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_a = grad_y_pred.sum()
    grad_b = (grad_y_pred * x).sum()
    grad_c = (grad_y_pred * x ** 2).sum()
    grad_d = (grad_y_pred * x ** 3).sum()

    # Update weights using gradient descent
    a -= learning_rate * grad_a
    b -= learning_rate * grad_b
    c -= learning_rate * grad_c
    d -= learning_rate * grad_d


print(f'Result: y = {a.item()} + {b.item()} x + {c.item()} x^2 + {d.item()} x^3')

99 4432.6962890625
199 2954.853759765625
299 1971.5645751953125
399 1317.07275390625
499 881.2531127929688
599 590.91796875
699 397.41290283203125
799 268.38140869140625
899 182.29763793945312
999 124.83570098876953
1099 86.45770263671875
1199 60.81041717529297
1299 43.66011047363281
1399 32.184268951416016
1499 24.500186920166016
1599 19.351442337036133
1699 15.898916244506836
1799 13.582014083862305
1899 12.025989532470703
1999 10.980072021484375
Result: y = 0.026494598016142845 + 0.8186383247375488 x + -0.0045707570388913155 x^2 + -0.08791063725948334 x^3


In [4]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

## **Introduction to Tensors**

### Creating Tensors

PyTorch tensors are created using `torch.Tensors()` = https://pytorch.org/docs/stable/tensors.html

In [5]:
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as python int
scalar.item()

7

In [8]:
# vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX

MATRIX = torch.tensor([[7,8],   
                        [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
MATRIX[0]

tensor([7, 8])

In [15]:
MATRIX[1]

tensor([ 9, 10])

In [16]:
# TENSOR 

TENSOR = torch.tensor([[[[1,2,3],
                        [4,5,6],
                        [7,8,9]]]])

TENSOR

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [17]:
TENSOR.ndim

4

In [18]:
TENSOR.shape

torch.Size([1, 1, 3, 3])

In [19]:
TENSOR[0]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [20]:
TENSOR_1 = torch.tensor([[[[
                        [1,2,3,4,5,6],
                        [6,5,4,3,2,1],
                        [1,2,3,4,5,6]]]]])

TENSOR_1

tensor([[[[[1, 2, 3, 4, 5, 6],
           [6, 5, 4, 3, 2, 1],
           [1, 2, 3, 4, 5, 6]]]]])

In [21]:
TENSOR_1.ndim

5

In [22]:
TENSOR_1.shape

torch.Size([1, 1, 1, 3, 6])

### Random Tensors

Why random tensors?

Random Tensors are important because the way many neural networks lern is that they start with tensors full of random numbers and then adjust those random numbers adjust those random numbers to better represent the data. 

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random Tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [23]:
# create a random tensors of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8843, 0.5099, 0.3623, 0.2555],
        [0.1360, 0.8402, 0.7483, 0.8025],
        [0.6147, 0.9987, 0.4203, 0.0775]])

In [24]:
random_tensor.ndim, random_tensor.shape

(2, torch.Size([3, 4]))

In [25]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.4377, 0.4590, 0.8795, 0.6902],
         [0.3071, 0.1578, 0.5848, 0.3208],
         [0.4436, 0.0863, 0.8090, 0.1787]]])

In [26]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.4816, 0.7092, 0.8060, 0.2183],
         [0.4048, 0.9750, 0.3352, 0.9232],
         [0.6219, 0.5689, 0.7164, 0.2723]]])

In [27]:
random_tensor.ndim

3

In [28]:
random_tensor.shape

torch.Size([1, 3, 4])

In [29]:
# create a random tensor with similar sha[e to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [30]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [33]:
# use torch.range()
one_to_ten = torch.arange(start=1,end=15,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
# creating tensors like
ten_zeros = torch.ones_like(input=one_to_ten)
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes

**NOTE** tensor datatypes is one of the 3 big error with pytorch and deep learning.

1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device

In [36]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0,9.0], 
                                dtype=None,     #What dataatype is the tensor (e.g. float32 or float16)
                                device=None,    # what device is your tensor on
                                requires_grad=False) #whether or not track gradients with this tensor operation

float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [37]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [38]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [39]:
int_32_tensor = torch.tensor([3,6,7,], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 7], dtype=torch.int32)

In [40]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 63.])

### Getting information from tensors

1. Tensor not right datatype - to do get datatype from a tensor, can use 'tensor.dtype'
2. Tensor not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensor not on the right device - to get device from a tensor, can use `tensor.device`

In [41]:
# Create a tensor 
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9105, 0.4772, 0.9619, 0.9597],
        [0.6164, 0.9020, 0.4403, 0.6058],
        [0.9037, 0.9845, 0.1867, 0.4096]])

In [42]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [43]:
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.9105, 0.4772, 0.9619, 0.9597],
        [0.6164, 0.9020, 0.4403, 0.6058],
        [0.9037, 0.9845, 0.1867, 0.4096]])
Datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (Tensor Operations)

#### Tensor Operation include:
* Addition 
* Substraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [44]:
# creating a tensor
tensor = torch.tensor([1,2,3])
tensor + 10,  tensor

(tensor([11, 12, 13]), tensor([1, 2, 3]))

In [45]:
tensor * 10

tensor([10, 20, 30])

In [46]:
tensor - 10

tensor([-9, -8, -7])

In [47]:
# try out pytorch in-built function
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning 

1. Element-Wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices

There are two main rules that performing matrix multiplication need to satisfy:

1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` wont'work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [48]:
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [49]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.1358, 0.3531, 0.3591],
        [0.3525, 0.3523, 0.5049],
        [0.4102, 0.3941, 0.5756]])

In [50]:
# Element wise multiplication 
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [51]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [52]:
# Matrix multiplication by hand 
1 * 1 + 2 * 2 + 3 * 3

14

In [53]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 113 µs, sys: 33 µs, total: 146 µs
Wall time: 140 µs


tensor(14)

In [54]:
%%time 

value = 0 
for i in range(len(tensor)):
    value += tensor[i] + tensor[i]
print(value)

tensor(12)
CPU times: user 1.2 ms, sys: 1.06 ms, total: 2.26 ms
Wall time: 1.37 ms


### One of the most common error in deep learning: Shape errors  

In [55]:
# Shapes for matrix multiplications
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for wrting less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [56]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensor using  a **transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [57]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [58]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [59]:
tensor_B.T.shape

torch.Size([2, 3])

In [60]:
# The matrix multiplication operation works when tensor_B is trnaposed 
print(f"Original shape: tensor_A= {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"new shape: tensor_A= {tensor_A.shape}(same shape as above), tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\n output shape: {output.shape}")

Original shape: tensor_A= torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
new shape: tensor_A= torch.Size([3, 2])(same shape as above), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

 output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [61]:
# create a tensor 
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [62]:
# Find the min
torch.min(x)

tensor(0)

In [63]:
torch.max(x)

tensor(90)

In [64]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [65]:
# Find the mean - note: the torch .mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32))

tensor(45.)

In [66]:
# Find the sum
torch.sum(x)

tensor(450)

### Finding the positional min and max of tensors

In [67]:
# finding the postion in tensor that has the minimum value with argmin() -> returns index position of terget tensors where the minimum value occurs 

torch.argmin(x)

tensor(0)

In [68]:
x[0]

tensor(0)

In [69]:
# finding the postion in tensor that has the maximum value with argmax() -> returns index position of terget tensors where the maximum value occurs
torch.argmax(x)

tensor(9)

In [70]:
x[9]

tensor(90)

### Reshaping, viewing, stacking, squeezing and unsqueezing tensors 

* Reshaping - reshape an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side(hstack) 
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor 
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [108]:
# Let's create a tensor

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [109]:
# Add extra dimension
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [110]:
# Add extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [78]:
# Add extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [84]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [85]:
x_reshaped = x.reshape(5, 2)
x_reshaped

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [86]:
# change the view
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [87]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [89]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [94]:
# Stack tensor on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0) 
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [98]:
x_vstacked = torch.vstack([x,x,x,x,x])
x_vstacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [102]:
x_hstacked = torch.hstack([x,x])
x_hstacked

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [116]:
# torch.squeeze() - remove all singe dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}") 
print(f"Preivious shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Preivious shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [123]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Privious target: {x_squeezed}")
print(f"Privious shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New Shape: {x_unsqueezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New Shape: {x_unsqueezed.shape}")


Privious target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Privious shape: torch.Size([9])

New Tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Shape: torch.Size([1, 9])

New Tensor: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New Shape: torch.Size([9, 1])


#### You can also rearrange the order of axes values with `torch.permute`(input, dims), where the input gets turned into a view with new dims.

In [135]:
x_original = torch.rand(size = (224, 224, 3)) # [Height, width, colour_channels]

# Permute the original tensor to arrange the axis (or dim) order
x_permute = torch.permute(x_original, (2, 0, 1))  # shifts axis 0->1, 1->2, 2->0 

print(f"Privious shape: {x_original.shape}")
print(f"\nNew Shape: {x_permute.shape}")

Privious shape: torch.Size([224, 224, 3])

New Shape: torch.Size([3, 224, 224])


In [138]:
x_original[0,0,0] = 123456
x_original[0,0,0], x_permute[0,0,0]

(tensor(123456.), tensor(123456.))

### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with numpy 

In [139]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [142]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [143]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [146]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0], x[0][0][1], x[0][0][2]

(tensor(1), tensor(2), tensor(3))

In [152]:
# you can also use  ":" to select "all" of a targeet dimension
x[:, :, 2]

tensor([[3, 6, 9]])

In [155]:
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [156]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 2]

tensor([[3, 6, 9]])

In [158]:
x[:, 1, 2]

tensor([6])

In [163]:
x[0, 0, :], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [166]:
x[0, 1:3, 1:3]

tensor([[5, 6],
        [8, 9]])

### PyTorch tensor & NumPy

NumPy is a popular scientific Python numerical computing library. 

And because of this, PyTorch has finctionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [173]:
# Numpy array to tensor 
import torch
import numpy as np 

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [174]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [175]:
array = array +1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [180]:
# Tensor to NumPy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [181]:
tensor.dtype, numpy_tensor.dtype

(torch.float32, dtype('float32'))

In [182]:
# change the tensor, what happeds to `numpy_tensor`?

tensor = tensor + 1
tensor

tensor([2., 2., 2., 2., 2., 2., 2.])

### Reproducibility (trying to take random out of random)

In short how a neural network learns:

` start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again ->again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness

In [189]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4763, 0.3438, 0.0083, 0.6398],
        [0.6595, 0.9471, 0.8482, 0.8049],
        [0.7355, 0.8781, 0.6003, 0.4795]])
tensor([[0.7424, 0.1825, 0.8542, 0.3631],
        [0.6103, 0.4257, 0.0967, 0.6864],
        [0.3794, 0.6713, 0.6351, 0.4653]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [198]:
# Let's make some random but reproducible tensor 
# set the random seed 
random_seed = 42 
torch.manual_seed(random_seed)
random_seed_c = torch.rand(3,4)
torch.manual_seed(random_seed)
random_seed_d = torch.rand(3,4)

print(f"Random seed C: {random_seed_c}")
print(f"Random seed D: {random_seed_d}")
print(random_seed_c == random_seed_d)

Random seed C: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Random seed D: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


#### Extra resources for reproducibility:

* https://pytorch.org/docs/stable/notes/randomness.html
* https://www.w3schools.com/python/ref_random_seed.asp

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory(Good):

### 1. Getting a GPU

1.  Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2.  Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's a lots of option... see this post what option get
3.  Use cloud computing  - GCP, AWS, Azur, these service allow you to rent cloud and access them

For 2 + 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do the refer to PyTorch setup Documents

https://pytorch.org/docs/stable/notes/cuda.html

In [200]:
# Check the GPU accesse with PyTorch
import torch

torch.cuda.is_available()

False

In [201]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [204]:
# cuda number of devices 
torch.cuda.device_count()

0

## Putting tensors (and models) on the GPU

The reason we want tensors/models on the GPU is because using a GPU results in faster computations

In [206]:
x = tensor.to(device)

In [207]:
x.numpy()

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [208]:
x.cpu().numpy()

array([2., 2., 2., 2., 2., 2., 2.], dtype=float32)

In [209]:
x

tensor([2., 2., 2., 2., 2., 2., 2.], device='mps:0')

#### Exercises

In [211]:
import torch

a = torch.rand(7,7)
a, a.shape

(tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036],
         [0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041],
         [0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591],
         [0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477],
         [0.6524, 0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331],
         [0.9578, 0.3313, 0.3227, 0.0162, 0.2137, 0.6249, 0.4340],
         [0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816]]),
 torch.Size([7, 7]))

In [213]:
b = torch.rand(1,7)
b, b.shape

(tensor([[0.0600, 0.2846, 0.2007, 0.5014, 0.3139, 0.4654, 0.1612]]),
 torch.Size([1, 7]))

In [215]:
torch.matmul(a, b.T)

tensor([[1.1717],
        [0.9437],
        [0.9601],
        [0.8217],
        [1.0516],
        [0.6525],
        [0.3525]])

In [219]:
torch.manual_seed(0)
a = torch.rand(7,7)
torch.manual_seed(0)
b = torch.rand(1,7)

a, b

torch.matmul(a, b.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [221]:
torch.manual_seed(1234)
a = torch.rand(1,7)
torch.manual_seed(1234)
b = torch.rand(1,7)

a, b

(tensor([[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518]]),
 tensor([[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518]]))

In [229]:
torch.manual_seed(1234)
q = torch.rand(2,3).to(device= "cpu")
torch.manual_seed(1234)
p = torch.rand(2,3)
q, p

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]))

In [232]:
w = torch.matmul(q, p.T)
w

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]])

In [234]:
torch.max(w), w.min()

(tensor(0.6287), tensor(0.2161))

In [237]:
r = torch.rand(1,8)
r

tensor([[0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313, 0.6012, 0.3043]])

In [238]:
r.argmax(), r.argmin()

(tensor(5), tensor(4))

In [240]:
t = torch.rand(1,1,1,10)
t

tensor([[[[0.7893, 0.3216, 0.5247, 0.6688, 0.8436, 0.4265, 0.9561, 0.0770,
           0.4108, 0.0014]]]])

In [251]:
z = t.squeeze()
z, z.shape

(tensor([0.7893, 0.3216, 0.5247, 0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108,
         0.0014]),
 torch.Size([10]))

In [254]:
torch.manual_seed(7)
d = torch.rand(1,1,1,10)
e = d.squeeze()
d, e, e.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))